* create button
** (!) should be selected first
** rect
** n-gon shape shows slider for point count
** polyline
** also artifacts? would make sense
* zoom
* settings
** grid size
** snap to grid (translate rotate etc; also translate/rotate + alt = snap to horizontal/vertical or 5 degree increments (so we must show the degrees))

* visible versions can be a strip instead of individual lines
** button: none/all/next/subsequent/strip (current version is always visible)
* effects
** chamfer etc

* selecting a group and trying to alter vertices doesn't work
* erode only selected edges
* expand selection/group
* edge mode
* "show floor polygons"
* fix the 3d view - super bad ergonomics right now
* make it more clear when drilled into group
* selection of overlapping vertices
* locking of polygons? unlock works then with cmd + click
* unchain
* version management
* double click for paths cause enter enters 3d view
* paths in groups?

* shortcuts
  c - create shape; cr - rect; cn - n-gon; cv - polyline; ca - artefact; cp - path
    mode in UI; drag - creates shape (or click in case of artefact or click + click + ... in the case of polyline or path)
  e - edit; ep - points; ee - edges; ep - polys (artefacts are always selectable)
    mode in UI; t - translate; r - rotate; s - scale; groups; selection (+selection stack for each element), direct selection;
  e - effects; ec - chamfer; en - noise
    click on poly / group & drag

  v - versions; vn/arrow down (global) - next; vp/arrow up (global) - prev
  bb - bake

  // p - paths; same as in points mode
  // a - artifacts
  // p - points; + - add points; - delete points; click - select; drag - marquee; shift+selection gesture - add to selection
  // t - select; tt - translate; tr - rotate; ts - scale; te - erode; gg/cmd+g - group; gu/cmd-shift-g - ungroup; click - select group; cmd+click - select poly; drag - marquee; shift+selection gesture - add to selection

  questions
    create a rect and want to move/scale it right away? friction
    create an artefact but want to move it? friction
    want to edit edge? have to click on edge first - friction
* UI
  pressing ? overlays tooltips on everything that is visible

  statusbar
  above that - group breadcrumbs, if any
  above that - baking progressbar if any

  bake button where?
  3d view button where?

  version strip where?

  delink button where?

* sound
  dinosaurs?
  https://www.youtube.com/watch?v=Fqf8EYdCehw

* marketing
** https://www.youtube.com/watch?v=90ImoX_e8nE

